name: Bug Report
description: File a new bug report to help us improve
title: "[BUG] Problem title"
labels: ["bug"]
assignees:
  - porto1090
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "A bug needs to be solved!"
    validations:
      required: true

  - type: dropdown
    id: projects
    attributes:
      label: Project
      description: Select the project where the issue occurred.
      multiple: true
      options:
        - 01 - Portfolio
        - 02 - CHAT-GPT
        - 03 - Project 3
        - 04 - Project 4

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: Check all that apply to describe the impact of this issue.
      options:
        - label: High priority - prevents usage of the project
          required: true
        - label: Medium priority - affects functionality but there are workarounds
          required: true
        - label: Low priority - minor issue
          required: true
